require:
- rubocop-rake
- rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# Layout/LineLength:
#   Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
